#!/usr/bin/env python3
"""midi2tones.py v4 — voice-aware conversion: dedup, priority, one fixed channel per voice.

Usage:
    pip install mido
    python midi2tones.py input.mid bgm > src/tunes/bgm.h

Strategy:
  1. Group notes into "voices" by MIDI channel, skipping percussion (ch10)
  2. Keep only one copy of voices with identical content (drops doubled tracks)
  3. Sort by average pitch: the highest voice is the melody -> always gets
     channel 0 and is never sacrificed
  4. Keep the first MAX_CHANNELS voices, each pinned to one output channel
  5. Make each voice monophonic: a new note steals from the old one
     (truncates the previous note — classic chiptune behavior)
"""
import sys
import mido

MAX_CHANNELS = 3          # melody+harmony+bass = original GB lineup. 2 drops the last voice
MIN_NOTE_MS = 25
NOTE_GAP_MS = 15          # gap at note tails: kills seam pops, adds staccato grain
MIN_FREQ = 180.0          # shift notes below this up an octave (tiny speaker can't drive them)
PERCUSSION_CH = 9

def midi_note_to_freq(n: int) -> float:
    return 440.0 * (2 ** ((n - 69) / 12.0))

def main(path: str, name: str):
    sym = "TUNE_" + name.upper()
    mid = mido.MidiFile(path)

    # --- Collect: one voice per MIDI channel as (note, start_ms, end_ms) ---
    voices = {}               # midi_ch -> [(start, note, end), ...]
    active, now = {}, 0.0
    for msg in mid:           # iterating the merged stream converts tempo automatically
        now += msg.time * 1000.0
        if msg.type not in ('note_on', 'note_off') or msg.channel == PERCUSSION_CH:
            continue
        key = (msg.channel, msg.note)
        if msg.type == 'note_on' and msg.velocity > 0:
            active[key] = now
        else:
            start = active.pop(key, None)
            if start is not None and now - start >= MIN_NOTE_MS:
                voices.setdefault(msg.channel, []).append((int(start), msg.note, int(now)))

    # --- Dedup: keep only one of any voices with identical note sequences ---
    seen, uniq = set(), []
    for ch, evs in voices.items():
        sig = tuple(evs)
        if sig in seen:
            sys.stderr.write("  channel %d: duplicate of another voice, skipped\n" % (ch+1))
            continue
        seen.add(sig)
        uniq.append((ch, evs))

    # --- Priority: average pitch high to low (melody on top) ---
    uniq.sort(key=lambda v: -sum(n for _, n, _ in v[1]) / len(v[1]))
    kept = uniq[:MAX_CHANNELS]
    for ch, evs in uniq[MAX_CHANNELS:]:
        sys.stderr.write("  channel %d: beyond MAX_CHANNELS, dropped (%d notes)\n" % (ch+1, len(evs)))

    # --- One output channel per voice + monophonize (new note truncates old) ---
    out = []
    for out_ch, (ch, evs) in enumerate(kept):
        evs.sort()
        mono = []
        for start, note, end in evs:
            while mono and mono[-1][0] >= start:   # simultaneous chord: keep the highest note
                if note >= mono[-1][1]: mono.pop()
                else: note = None; break
            if note is None: continue
            if mono and mono[-1][2] > start:       # overlap: truncate the previous note
                s, n, _ = mono[-1]; mono[-1] = (s, n, start)
            mono.append((start, note, end))
        avg = sum(n for _, n, _ in mono)/len(mono)
        sys.stderr.write("  voice %d <- midi ch %d: %d notes, avg pitch %.0f\n"
                         % (out_ch, ch+1, len(mono), avg))
        for start, note, end in mono:
            dur = end - start
            if dur < MIN_NOTE_MS: continue
            freq = midi_note_to_freq(note)
            while freq < MIN_FREQ: freq *= 2
            out.append((start, freq, dur, out_ch))

    out.sort()
    total_s = max(e[0]+e[2] for e in out)/1000.0 if out else 0
    sys.stderr.write("[%s] total %d notes, %.1f s\n" % (name, len(out), total_s))

    print("// generated by midi2tones.py v4 — slot '%s', %d notes, %.1f s" % (name, len(out), total_s))
    print("#pragma once")
    print('#include "../tune_types.h"')
    print("static const ToneEvent %s_EV[] = {" % sym)
    for start, freq, dur, ch in out:
        play = max(dur - NOTE_GAP_MS, 20)
        print("  {%u, %u, %u, %u}," % (start, round(freq), min(play, 65535), ch))
    print("};")
    print("static const Tune %s = { %s_EV, sizeof(%s_EV)/sizeof(%s_EV[0]) };" % (sym, sym, sym, sym))

if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.exit("usage: midi2tones.py input.mid <slot_name>")
    main(sys.argv[1], sys.argv[2])
