#!/usr/bin/env python3
"""wav2raw.py — convert a WAV sound effect into a PCM slot header that
compiles straight into the firmware.

Usage:
    python wav2raw.py deny.wav deny       > src/tunes/deny.h   (default gain 0.4)
    python wav2raw.py deny.wav deny 0.25  > src/tunes/deny.h   (quieter)

The third argument is gain 0.05~1.0. Samples are normalized first and then
scaled by this factor, so WAVs from different sources end up with consistent
loudness at the same number.

Only uncompressed PCM WAV is supported (8/16-bit, mono or stereo). Export
mp3 or other compressed formats to WAV with any audio tool first.
Pure Python standard library — nothing to install.
"""
import sys, wave, struct

TARGET_RATE = 16000     # output sample rate: 16kHz is plenty for the tiny speaker, saves flash

def main(path: str, name: str, gain: float):
    sym = "TUNE_" + name.upper()
    w = wave.open(path, 'rb')
    nch, width, rate, nframes = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
    raw = w.readframes(nframes)
    w.close()

    # Decode to float mono (-1.0 ~ 1.0)
    if width == 2:
        samples = struct.unpack('<%dh' % (len(raw)//2), raw)
        mono = [sum(samples[i:i+nch])/nch/32768.0 for i in range(0, len(samples), nch)]
    elif width == 1:        # 8-bit WAV is unsigned
        mono = [ (sum(raw[i:i+nch])/nch - 128)/128.0 for i in range(0, len(raw), nch)]
    else:
        sys.exit("unsupported sample width: %d bytes" % width)

    # Linear-interpolation resample to TARGET_RATE
    n_out = int(len(mono) * TARGET_RATE / rate)
    out = []
    for i in range(n_out):
        pos = i * (len(mono)-1) / max(n_out-1, 1)
        a, frac = int(pos), pos - int(pos)
        v = mono[a]*(1-frac) + mono[min(a+1, len(mono)-1)]*frac
        out.append(v)

    # Normalize first (removes source loudness differences), then apply the
    # requested gain and convert to signed 8-bit.
    peak = max(0.0001, max(abs(v) for v in out))
    pcm = [max(-127, min(127, round(v/peak*gain*127))) for v in out]

    kb = len(pcm)/1024.0
    sys.stderr.write("[%s] %.2f s @ %dHz, gain=%.2f -> %.1f KB flash\n"
                     % (name, len(pcm)/TARGET_RATE, TARGET_RATE, gain, kb))
    if kb > 300:
        sys.stderr.write("warning: large output — consider trimming, or use PCM only for short effects\n")

    print("// generated by wav2raw.py — slot '%s', %.2f s PCM @ %dHz"
          % (name, len(pcm)/TARGET_RATE, TARGET_RATE))
    print("#pragma once")
    print('#include "../tune_types.h"')
    print("static const int8_t %s_PCM[] = {" % sym)
    for i in range(0, len(pcm), 24):
        print("  " + ",".join(str(v) for v in pcm[i:i+24]) + ",")
    print("};")
    print("static const Tune %s = { nullptr, 0, %s_PCM, sizeof(%s_PCM), %d };"
          % (sym, sym, sym, TARGET_RATE))

if __name__ == '__main__':
    if len(sys.argv) not in (3, 4):
        sys.exit("usage: wav2raw.py input.wav <slot_name> [gain 0.05~1.0]")
    g = float(sys.argv[3]) if len(sys.argv) == 4 else 0.4
    g = max(0.05, min(1.0, g))
    main(sys.argv[1], sys.argv[2], g)
